import NavBar from "@/components/NavBar";

//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";

//core
import "primereact/resources/primereact.min.css";

//icons
import "primeicons/primeicons.css";

import "@/styles/globals.css";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Snack&Chill</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://img.freepik.com/vector-premium/papas-fritas-tazon-estilo-pixel-art_475147-876.jpg?w=360"
        />
      </Head>
      <div
        style={{
          display: "grid",
          gridTemplateRows: "75px 1fr",
          gap: "15px",
          
        }}
      >
        <NavBar />
        <Component {...pageProps} />
      </div>
    </>
  );
}
